// Everything the SQL guard accepts by name. Anything absent is rejected, so a
// dangerous function that nobody thought of is blocked by default (D-23).

export const EXPOSED_SCHEMA = 'sales';

// Must match the tables granted to app_readonly by the migrations; an
// integration test compares this list with the grants in the database.
export const EXPOSED_TABLES: ReadonlySet<string> = new Set([
  'regions',
  'products',
  'customers',
  'orders',
  'order_items',
  'distribution_centers',
  'stock_levels',
  'stock_movements',
]);

// Functions and types may only be unqualified or qualified with this schema.
export const SYSTEM_SCHEMA = 'pg_catalog';

const AGGREGATE_FUNCTIONS = [
  'count',
  'sum',
  'avg',
  'min',
  'max',
  'string_agg',
  'array_agg',
  'bool_and',
  'bool_or',
  'every',
  'stddev',
  'stddev_pop',
  'stddev_samp',
  'variance',
  'var_pop',
  'var_samp',
  'percentile_cont',
  'percentile_disc',
  'mode',
  'corr',
];

const WINDOW_FUNCTIONS = [
  'row_number',
  'rank',
  'dense_rank',
  'percent_rank',
  'cume_dist',
  'ntile',
  'lag',
  'lead',
  'first_value',
  'last_value',
  'nth_value',
];

const MATH_FUNCTIONS = [
  'abs',
  'round',
  'ceil',
  'ceiling',
  'floor',
  'trunc',
  'mod',
  'div',
  'power',
  'sqrt',
  'sign',
  'ln',
  'log',
  'exp',
];

// Left out on purpose: repeat, lpad, rpad and format can build arbitrarily
// large strings from a small query.
const TEXT_FUNCTIONS = [
  'lower',
  'upper',
  'initcap',
  'length',
  'char_length',
  'character_length',
  'trim',
  'btrim',
  'ltrim',
  'rtrim',
  'substring',
  'substr',
  'left',
  'right',
  'replace',
  'concat',
  'concat_ws',
  'position',
  'strpos',
  'split_part',
  'to_char',
  'to_number',
  // Generated by the parser for LIKE ... ESCAPE and SIMILAR TO.
  'like_escape',
  'similar_to_escape',
];

const DATE_FUNCTIONS = [
  'now',
  'date_trunc',
  'date_part',
  'extract',
  'age',
  'to_date',
  'to_timestamp',
  'make_date',
  'date_bin',
  // Generated by the parser for AT TIME ZONE.
  'timezone',
];

const SET_RETURNING_FUNCTIONS = ['generate_series'];

export const ALLOWED_FUNCTIONS: ReadonlySet<string> = new Set([
  ...AGGREGATE_FUNCTIONS,
  ...WINDOW_FUNCTIONS,
  ...MATH_FUNCTIONS,
  ...TEXT_FUNCTIONS,
  ...DATE_FUNCTIONS,
  ...SET_RETURNING_FUNCTIONS,
]);

// Target types of a cast. The reg* types (regclass, regproc...) are left out:
// casting to them looks objects up in the system catalog.
export const ALLOWED_TYPES: ReadonlySet<string> = new Set([
  'int2',
  'int4',
  'int8',
  'smallint',
  'integer',
  'bigint',
  'numeric',
  'decimal',
  'float4',
  'float8',
  'real',
  'text',
  'varchar',
  'bpchar',
  'bool',
  'boolean',
  'date',
  'time',
  'timetz',
  'timestamp',
  'timestamptz',
  'interval',
]);

// CURRENT_USER, SESSION_USER, CURRENT_CATALOG and the like are not listed:
// they reveal how the application connects.
export const ALLOWED_SQL_VALUE_FUNCTIONS: ReadonlySet<string> = new Set([
  'SVFOP_CURRENT_DATE',
  'SVFOP_CURRENT_TIME',
  'SVFOP_CURRENT_TIME_N',
  'SVFOP_CURRENT_TIMESTAMP',
  'SVFOP_CURRENT_TIMESTAMP_N',
  'SVFOP_LOCALTIME',
  'SVFOP_LOCALTIME_N',
  'SVFOP_LOCALTIMESTAMP',
  'SVFOP_LOCALTIMESTAMP_N',
]);
